# hpa-board.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: board-hpa
  namespace: nt114
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: board
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80