name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - "column-service/**"  # Chỉ chạy khi có thay đổi trong thư mục column-service
  pull_request:
    branches:
      - main
    paths:
      - "column-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cài đặt dependencies
        run: npm ci
        working-directory: ./column-service  # Đảm bảo lệnh chạy trong thư mục đúng

      - name: Xây dựng
        run: npm run build -- --verbose
        env:
          NODE_ENV: production
        working-directory: ./column-service
        continue-on-error: false

      - name: Chạy kiểm thử (nếu có)
        run: npm test -- --verbose || echo "Không có kiểm thử, bỏ qua bước này"
        env:
          NODE_ENV: test
        working-directory: ./column-service
        continue-on-error: true  # Bỏ qua nếu không có kiểm thử

      - name: Hiển thị chi tiết lỗi build
        if: failure()
        run: |
          echo "Kiểm tra các file log lỗi..."
          find . -type f -name "*.log" -exec cat {} \; || echo "Không tìm thấy file log"
          echo "Liệt kê các file trong thư mục build (nếu có)..."
          ls -la dist/ || echo "Không tìm thấy thư mục dist/"
        working-directory: ./column-service