version: '3.8'

services:
  # Microservice: card
  card:
    image: thuan410/nt114-be-card:v1
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: column
  column:
    image: thuan410/nt114-be-column:v1
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: board
  board:
    image: thuan410/nt114-be-board:v1
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: user
  user:
    image: thuan410/nt114-be-user:v1
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

# Định nghĩa network để các container giao tiếp với nhau
networks:
  app-network:
    driver: bridge
