version: '3.8'
services:

  mongodb:
    image: mongo:7
    container_name: nt114-mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

  user:
    image: thuan410/user-service:latest
    container_name: nt114-user-service
    env_file:
      - ./envs/user-service.env
    networks:
      - app-network
      - shared-network
    restart: unless-stopped

  board:
    image: thuan410/board-service:latest
    container_name: nt114-board-service
    env_file:
      - ./envs/board-service.env
    environment:
      - USER_SERVICE_URL=http://user:3001
      - COLUMN_SERVICE_URL=http://column:3003
      - CARD_SERVICE_URL=http://card:3004
      - INVITATION_SERVICE_URL=http://invitation:3005
    depends_on:
      - user
    networks:
      - app-network
      - shared-network
    restart: unless-stopped

  column:
    image: thuan410/column-service:latest
    container_name: nt114-column-service
    env_file:
      - ./envs/column-service.env
    environment:
      - USER_SERVICE_URL=http://user:3001
      - BOARD_SERVICE_URL=http://board:3002
      - INVITATION_SERVICE_URL=http://invitation:3005
    depends_on:
      - user
      - board
    networks:
      - app-network
      - shared-network
    restart: unless-stopped

  card:
    image: thuan410/card-service:latest
    container_name: nt114-card-service
    env_file:
      - ./envs/card-service.env
    environment:
      - USER_SERVICE_URL=http://user:3001
      - BOARD_SERVICE_URL=http://board:3002
      - COLUMN_SERVICE_URL=http://column:3003
      - INVITATION_SERVICE_URL=http://invitation:3005
    depends_on:
      - user
      - column
    networks:
      - app-network
      - shared-network
    restart: unless-stopped

  invitation:
    image: thuan410/notification-service:latest
    container_name: nt114-invitation-service
    env_file:
      - ./envs/notification-service.env
    environment:
      - USER_SERVICE_URL=http://user:3001
      - BOARD_SERVICE_URL=http://board:3002
      - COLUMN_SERVICE_URL=http://column:3003
      - CARD_SERVICE_URL=http://card:3004
    depends_on:
      - user
    networks:
      - app-network
      - shared-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  shared-network:
    external: true

volumes:
  mongo-data: