version: '3.8'

services:
  # Microservice: invitation
  invitation:
    build:
      context: ./notification-service
    image: nt114-microservice-be-invitation:latest
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: card
  card:
    build:
      context: ./card-service
    image: nt114-microservice-be-card:latest
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: column
  column:
    build:
      context: ./column-service
    image: nt114-microservice-be-column:latest
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: board
  board:
    build:
      context: ./board-service
    image: nt114-microservice-be-board:latest
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

  # Microservice: user
  user:
    build:
      context: ./user-service
    image: nt114-microservice-be-user:latest
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/
      - DATABASE_NAME=NT114
    networks:
      - app-network

# Định nghĩa network để các container giao tiếp với nhau
networks:
  app-network:
    driver: bridge