apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: nt114
data:
  REACT_APP_USER_SERVICE_URL: "http://192.168.88.31:30001/api/users"
  REACT_APP_BOARD_SERVICE_URL: "http://192.168.88.31:30002/api/boards"
  REACT_APP_COLUMN_SERVICE_URL: "http://192.168.88.31:30003/api/columns"
  REACT_APP_CARD_SERVICE_URL: "http://192.168.88.31:30004/api/cards"
  REACT_APP_INVITATION_SERVICE_URL: "http://192.168.88.31:30005/api/invitations"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: nt114
data:
  USER_PORT: "3001"
  BOARD_PORT: "3002"
  COLUMN_PORT: "3003"
  CARD_PORT: "3004"
  INVITATION_PORT: "3005"
  DATABASE_NAME: "NT114"
  USER_SERVICE_URL: "http://192.168.88.31:30001"
  BOARD_SERVICE_URL: "http://192.168.88.31:30002"
  COLUMN_SERVICE_URL: "http://192.168.88.31:30003"
  CARD_SERVICE_URL: "http://192.168.88.31:30004"
  INVITATION_SERVICE_URL: "http://192.168.88.31:30005"
root@k8s-master-1:/kubernetes/project/nt114# cat secret.yaml
# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: nt114
type: Opaque
stringData:
  API_KEY: api-key-example  # Giá trị văn bản thô, không cần mã hóa Base64
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: nt114
type: Opaque
stringData:
  mongo-uri: mongodb+srv://thuantv:22521448@cluster0.nopqraq.mongodb.net/  # Giá trị văn bản thô
  jwt-secret: tranthuan410  # Giá trị văn bản thô