# board.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board
  namespace: nt114
  labels:
    app: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board
        image: thuan410/nt114-be-board:v2  # Cập nhật image
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: BOARD_PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-uri
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DATABASE_NAME
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: USER_SERVICE_URL
        - name: COLUMN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: COLUMN_SERVICE_URL
        - name: CARD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: CARD_SERVICE_URL
        - name: INVITATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: INVITATION_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: board-service
  namespace: nt114
spec:
  selector:
    app: board
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002
    nodePort: 30002
  type: NodePort