# user.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: nt114
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: thuan410/nt114-be-user:v2  # Cập nhật image
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: USER_PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-uri
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: DATABASE_NAME
        - name: BOARD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: BOARD_SERVICE_URL
        - name: COLUMN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: COLUMN_SERVICE_URL
        - name: CARD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: CARD_SERVICE_URL
        - name: INVITATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: INVITATION_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt-secret
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: nt114
spec:
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
    nodePort: 30001
  type: NodePort