name: Notification Service CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]
      fail-fast: false

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: notification-service/package-lock.json

      - name: Cài đặt dependencies
        run: npm ci
        working-directory: ./notification-service

      - name: Xây dựng
        run: npm run build -- --verbose
        env:
          NODE_ENV: production
        working-directory: ./notification-service
        continue-on-error: false

      - name: Hiển thị chi tiết lỗi nếu thất bại
        if: failure()
        run: |
          echo "Kiểm tra các file log lỗi..."
          find . -type f -name "*.log" -exec cat {} \; || echo "Không tìm thấy file log"
          echo "Liệt kê các file trong thư mục build (nếu có)..."
          ls -la dist/ || echo "Không tìm thấy thư mục dist/"
        working-directory: ./notification-service