name: MicroService CI

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build-board-service:
    uses: ./.github/workflows/board-service.yml

  build-card-service:
    uses: ./.github/workflows/card-service.yml

  build-column-service:
    uses: ./.github/workflows/column-service.yml

  build-notification-service:
    uses: ./.github/workflows/notification-service.yml

  build-user-service:
    uses: ./.github/workflows/user-service.yml
