name: Monorepo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-services:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [board-service, card-service, column-service, notification-service, user-service]
      fail-fast: false  # Tiếp tục chạy các service khác nếu một service thất bại

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'  # Bạn có thể chọn phiên bản Node.js mặc định
          cache: 'npm'
          cache-dependency-path: ${{ matrix.service }}/package-lock.json  # Cache riêng cho từng service

      - name: Cài đặt dependencies cho ${{ matrix.service }}
        run: npm ci
        working-directory: ./${{ matrix.service }}

      - name: Xây dựng ${{ matrix.service }}
        run: npm run build -- --verbose
        env:
          NODE_ENV: production
        working-directory: ./${{ matrix.service }}
        continue-on-error: false

      - name: Hiển thị chi tiết lỗi build nếu thất bại
        if: failure()
        run: |
          echo "Kiểm tra các file log lỗi..."
          find . -type f -name "*.log" -exec cat {} \; || echo "Không tìm thấy file log"
          echo "Liệt kê các file trong thư mục build (nếu có)..."
          ls -la dist/ || echo "Không tìm thấy thư mục dist/"
        working-directory: ./${{ matrix.service }}