name: Monorepo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  discover-services:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Tìm các thư mục con chứa service
        id: set-services
        run: |
          # Chỉ liệt kê các thư mục *-service, bỏ qua scannerwork
          SERVICES=$(ls -d board-service card-service column-service notification-service user-service | jq -R -s -c 'split("\n")[:-1]')
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  report-services:
    needs: discover-services
    runs-on: ubuntu-latest
    steps:
      - name: Báo cáo các service được phát hiện
        run: |
          echo "Các service sẽ chạy CI: ${{ needs.discover-services.outputs.services }}"
          echo "Workflow CI của từng service sẽ tự động chạy dựa trên sự kiện push/pull_request và điều kiện paths."